version: '3'

networks:
  forgejo:
    external: false

services:
  server:
    image: codeberg.org/forgejo/forgejo:13.0.2
    container_name: forgejo
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA_CUSTOM=/data/gitea/
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
    restart: always
    networks:
      - forgejo
    volumes:
      - type: bind
        source: ./forgejo
        target: /data
        volume_opt:
          o: z  # Applique :Z pour permettre l'écriture
      - /etc/timezone:/etc/timezone:ro  # Lecture seule, pas besoin de :Z
      - /etc/localtime:/etc/localtime:ro # Lecture seule, pas besoin de :Z
    expose:
      - '3000'
    ports:
      - '22:22'
    depends_on:
      - db

  docker-in-docker:
    image: docker:dind
    container_name: 'docker_dind'
    privileged: 'true'
    command: ['dockerd', '-H', 'tcp://0.0.0.0:2375', '--tls=false']
    restart: 'unless-stopped'
    volumes:
      - type: bind
        source: ./dind
        target: /var/lib/docker
        volume_opt:
          o: Z

  runner:
    image: 'data.forgejo.org/forgejo/runner:11'
    links:
      - docker-in-docker
    depends_on:
      docker-in-docker:
        condition: service_started
    container_name: 'runner'
    environment:
      DOCKER_HOST: tcp://docker-in-docker:2375
    volumes:
      - ./runner:/data
    networks:
      - forgejo
    restart: 'unless-stopped'

    command: '/bin/sh -c "while : ; do sleep 1 ; done ;"'


  nginx:
    image: nginx:stable
    container_name: forgejo-proxy
    depends_on:
      - server
      - mkcert
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - '443:443'
    networks:
      - forgejo

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    networks:
      - forgejo
    volumes:
      - ./postgres:/var/lib/postgresql/data


  mkcert:
    image: alpine/mkcert
    container_name: mkcert
    volumes:
      - ./mkcert:/root/.local/share/mkcert  # Stocke l'autorité de certification locale
      - ./nginx/ssl:/ssl                    # Dossier où les certificats seront générés
    command: >
      sh -c "
      mkcert -install &&
      mkcert -cert-file /ssl/cert.pem -key-file /ssl/key.pem forgejo.local git.forgejo.local localhost 127.0.0.1 ::1 &&
      chmod 644 /ssl/*.pem
      "
    networks:
      - forgejo
